branch-defaults:
  master:
    environment: apiwalletcryptocurve-dev
    group_suffix: null
global:
  application_name: api.wallet.cryptocurve
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: cryptocurve
  repository: null
  sc: git
  workspace_type: Application
