
node {
  try {
    stage('Checkout') {
      checkout scm
    }
    stage('Environment') {
      sh 'git --version'
      echo "Branch: ${env.BRANCH_NAME}"
      sh 'docker -v'
      sh 'printenv'
    }
    stage('Deploy'){
        sh 'docker build -t apiwallet --no-cache .'
        sh 'docker tag apiwallet 577425357631.dkr.ecr.us-east-2.amazonaws.com/apiwallet'
        sh 'docker push 577425357631.dkr.ecr.us-east-2.amazonaws.com/apiwallet'
    }
  }
  catch (err) {
    throw err
  }
}
